[WID]メッセージ送信機能実装
y1mutsu/chat-space4 pull request #5
Opened 2019-03-06 01:44 UTC by y1mutsu

##what
メッセージ送信機能実装を行ないました

2019-03-06 02:12 UTC, TOMARUMARU commented on app/assets/stylesheets/modules/_fa_icon.scss
> +//   .hidden{
以下消しましょう

2019-03-06 02:12 UTC, TOMARUMARU commented on app/controllers/messages_controller.rb
> +      @messages = @group.messages.includes(:user)
elseにだけあるというのはどういうことなのでしょう？

2019-03-06 02:12 UTC, TOMARUMARU commented on app/views/messages/index.html.haml
> +          /s= f.label :image, class: 'form__mask__image' do
使用してなければ消しましょう

2019-03-06 02:37 UTC, y1mutsu commented on app/assets/stylesheets/modules/_fa_icon.scss
> +//   .hidden{
削除しました

2019-03-06 02:49 UTC, y1mutsu commented on app/controllers/messages_controller.rb
> +      @messages = @group.messages.includes(:user)
すみませんが、何が足りないのでしょうか？

2019-03-06 02:50 UTC, y1mutsu commented on app/views/messages/index.html.haml
> +          /s= f.label :image, class: 'form__mask__image' do
消しました

2019-03-06 05:30 UTC, miyagit commented on app/controllers/messages_controller.rb
> +      @messages = @group.messages.includes(:user)
こちら記述している意図について教えてください。

2019-03-06 05:45 UTC, hirozak commented on app/controllers/messages_controller.rb
> +      @messages = @group.messages.includes(:user)
なぜelse時にのみ@messagesを変数にしてますか？

2019-03-06 05:47 UTC, y1mutsu reviewed
誤りです。
訂正します。

2019-03-06 05:47 UTC, y1mutsu commented on app/controllers/messages_controller.rb
> +      @messages = @group.messages.includes(:user)
ヘルパーメソッドのsaveを使い、データーの有無を判断するために記入しております

2019-03-06 05:53 UTC, hirozak commented on app/controllers/messages_controller.rb
> +      @messages = @group.messages.includes(:user)
どういうことですか？
`@messages`は具体的にどういう時に必要なんですか？

2019-03-06 06:47 UTC, y1mutsu commented on app/controllers/messages_controller.rb
> +      @messages = @group.messages.includes(:user)
データーが複数あるときに使用します。

2019-03-07 06:58 UTC, miyagit commented on app/assets/stylesheets/modules/_chat_nav.scss
> +// .member_box{
不必要なコメントアウトは削除しましょう。

2019-03-07 07:04 UTC, y1mutsu commented on app/assets/stylesheets/modules/_chat_nav.scss
> +// .member_box{
削除しました。

2019-03-07 07:06 UTC, yuki-uchida requested changes
一点修正点あります。
pushは忘れずに！

2019-03-07 07:06 UTC, yuki-uchida commented on app/assets/stylesheets/modules/_chat_nav.scss
> +        color: #999999;
色は変数化しておきましょう。色管理用のscssを作成しておくことによってサイト全体の色統一、変更が容易になり可読性も上がります

2019-03-08 07:13 UTC, y1mutsu commented on app/assets/stylesheets/modules/_chat_nav.scss
> +        color: #999999;
行ないました！

2019-03-08 07:16 UTC, TOMARUMARU approved these changes
LGTM

2019-03-11 03:44 UTC, merged